channels:
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - azureml-core==1.19.0
  - azureml-defaults==1.19.0
  - azureml-telemetry==1.19.0
  - azureml-train-restclients-hyperdrive==1.19.0
  - azureml-train-core==1.19.0
  - tensorflow-gpu==2.0.0
  - keras<=2.3.1
  - matplotlib
  - scikit-learn==0.23.2
  - tqdm
name: keras_tensorflow_2.0.0
